version: "3.7"
services:
  idiet:
    build: ./IDiet
    image: johnhoman/idiet-frontend
    ports:
      - "127.0.0.1:3000:3000"
  tracking:
    build: ./tracking-server
    image: jackhoman/idiet-tracking
  postgres:
    # NOTE: postgres reuses labels for incompatable changes
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pa$$w0rd}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # this probably isn't necessary because postgres would only be access
      # inside the container
      - "127.0.0.1:5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pa$$w0rd}
    ports:
      - "127.0.0.1:5050:80"
    volumes:
      - pgadmin:/root/.pgadmin
volumes:
  pgdata:
  pgadmin:
